### ISSUE TITLE
The content is missing for the Shipping policy.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#11]
**The url:**
https://lovinwisk.com/pages/shipping-policy
**Actual result:**
The content is missing for the Shipping policy.
![image](https://user-images.githubusercontent.com/102131636/170244022-6e63eed2-a1a8-475b-a71a-7368aa854161.png)

**Expected result:**
The text content have to be added.

**Comment by devSharibAli** [comment]
client will provide later

**Comment by sudhanshu0603** [comment]
ok
