### ISSUE TITLE
The search bar icon is needs to aligned properly.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#19]
**Actual result:**
The search bar icon is not aligned properly.
![image](https://user-images.githubusercontent.com/102131636/170412330-af67feb5-006b-45da-8d1f-b93450cad960.png)

**Expected result:**
The aligned of search bar icon for the mobile view can be improved.

**Comment by ui-anilrana** [comment]
![1653463754947](https://user-images.githubusercontent.com/100346531/170430859-89778ece-91c0-44dc-b820-1dfe4a3da502.jpg)

No issue in real device

**Comment by ui-anilrana** [comment]
![image](https://user-images.githubusercontent.com/100346531/170431394-8408a17f-b397-4e23-add6-bcef7f066a19.png)


@sudhanshu0603  No isuue in real device

**Comment by sudhanshu0603** [comment]
In other pages, the logo is againing to its same place.
