### ISSUE TITLE
For the flag uk the name is given english.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#2]
**Actual result:**
For the flag uk the name is given english, when we click on the language converter on the header.
![image](https://user-images.githubusercontent.com/102131636/170231803-cca4e9b6-df4e-4b42-b938-635e1626326b.png)

**Expected result:**
The english name should be replaced with the  uk name as the flag is of uk.

**Comment by devSharibAli** [comment]
Coming from app can't be changed

**Comment by sudhanshu0603** [comment]
ok
