### ISSUE TITLE
The light white spacing is coming over the search bar.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#21]
**Actual result:**
The light white spacing is coming over the search bar.
![image](https://user-images.githubusercontent.com/102131636/170413195-ae43be27-4961-4c29-b1a8-63e1b6bf6638.png)

**Expected result:**
The search bar white spacing can be removed.

**Comment by ui-anilrana** [comment]
![image](https://user-images.githubusercontent.com/100346531/170432738-79e2f2e5-aeeb-4e64-9731-16f256db6fef.png)
 no issue find in device

**Comment by sudhanshu0603** [comment]
ok
