### ISSUE TITLE
Inside the hambergur, at the bottom white spacing is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#22]
**Actual result:**
The white spacing is coming inside the hambergur at the bottom.
![image](https://user-images.githubusercontent.com/102131636/170415409-f3e5ca93-8771-4f40-9132-437ca5f5b615.png)

**Expected result:**
The white spacing is coming inside the hambergur.

**Comment by ui-anilrana** [comment]
![image](https://user-images.githubusercontent.com/100346531/170434993-74ea8874-557f-468e-b1eb-1403e2e081ae.png)

no issue found

**Comment by sudhanshu0603** [comment]
ok
