### ISSUE TITLE
The images of the collection is not clickable in homepage.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#24]
**Actual result:**
The images of the collection is not clickable.
![image](https://user-images.githubusercontent.com/102131636/170424494-0ab7b2dd-09af-498b-9fc4-dff5bb880ec7.png)

**Expected result:**
The image of the collection also be clickable it will be much better.

**Comment by devSharibAli** [comment]
cta button is there so no need to make image clickable

**Comment by sudhanshu0603** [comment]
ok
