### ISSUE TITLE
The titles of the collection page for the mobile view can be aligned in centre it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#27]
**Actual result:**
The titles of the collection page for the mobile view can be aligned in centre it will be much better.
![image](https://user-images.githubusercontent.com/102131636/170427345-f07e379c-fc8d-4a5e-abad-0c76f96f8f6f.png)

**Expected result:**
The title of the collection page can be aligned in the centre it will be much better.

**Comment by ui-anilrana** [comment]
![image](https://user-images.githubusercontent.com/100346531/170443361-5030db75-59ca-4083-8c5f-5340ccdc03a9.png)

no issue found

**Comment by sudhanshu0603** [comment]
ok
