### ISSUE TITLE
The arrow of the dropdown is coming in between the border of dropdown.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#28]
**Actual result:**
The arrow of the dropdown is coming in between the border of dropdown.
![image](https://user-images.githubusercontent.com/102131636/170427650-9177703d-e743-401d-b854-031210eb2eca.png)
**Expected result:**
The arrow of the dropdown  can be aligned more properly.

**Comment by ui-anilrana** [comment]
![image](https://user-images.githubusercontent.com/100346531/170443545-d935f052-a57b-40d6-93ba-fdd634125b4f.png)

No issue found

**Comment by sudhanshu0603** [comment]
ok
