### ISSUE TITLE
After successfull login, in account page the for the buttons double borders are coming when we click on it.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Anthony-Store-Design#32]
**Actual result:** 
After successfull login, in account page the for the buttons double borders are coming when we click on it.
![image](https://user-images.githubusercontent.com/102131636/170431050-50bfc24c-1c19-4876-84dc-65f69260cdbf.png)

**Expected result:**
The double border should not come when we click on the buttons.

**Comment by ui-anilrana** [comment]
![image](https://user-images.githubusercontent.com/100346531/170449044-1df9a977-1a73-4e50-a45b-4dd424c1fb2d.png)

No issue found

**Comment by sudhanshu0603** [comment]
ok,
